version: 2
jobs:
   checkout:
     docker:
       - image: node:8.11.1-alpine
     steps:
       - checkout
       - persist_to_workspace:
          root: .
          paths:
            - .

   build:
     docker:
       - image: node:8.11.1-alpine
     steps:
       - attach_workspace:
          at: .
       - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
       - run:
          name: Install dependencies
          command: yarn install && yarn build
       - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
       - persist_to_workspace:
          root: .
          paths:
            - .

   test:
     docker:
       - image: node:8.11.1-alpine
     steps:
       - attach_workspace:
          at: .
       - run:
          name: Run linter
          command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build
